<?php
/*
 * Seznam vsech pouzitych textu v informacnim systemu
 *
 */
$text = array (

	'no_query'						=>			array('©patný sql dotaz.',
															'Bad SQL query.'),
	'table_full'					=>			array('Chyba dat.',
															'Eror od data'),
	// install.php
	'not_create_table'			=>			array('Nelze vytvoøit tabulku:',
															'Can not create table:'),
	'create_table'					=>			array('Tabulka vytvoøena.',
															'Table created.'),
	'n_create'						=>			array('Vytvoøí se tabulky.',
															'Tables will be created.'),
	'n_insert'						=>			array('Naplní se vytvoøené tabulky vzorem dat.',
															'Fill table sample of data.'),
	'not_insert_table'			=>			array('Nepovedlo se naplnit tabulku:',
															'Table is not filled:'),
	'insert_table'					=>			array('Tabulka je naplnìna daty.',
															'Table is filled by data.'),
	'author'							=>			array('Autoøi:',
															'Authors:'),
	'system_name'					=>			array('Instalace systému RT-Mistroství svìta ve fotbalu.',
															'Instalall system RT-FIFA World Cup.'),
	'system_install'				=>			array('Instalace:',
															'Install:'),
	'system_lang_cz'				=>			array('Èesky:',
															'Czech:'),
	'system_lang_eng'				=>			array('Anglicky:',
															'English:'),
	'xsendl00'						=>			array('Jaroslav Sendler - xsendl00.',
															'Jaroslav Sendler - xsendl00.'),
	'xkovac21'						=>			array('Du¹an Kovaèiè - xkovac21.',
															'Dusan Kovacic - xkovac21'),

	// login.php
	'empty_login'					=>			array('Nezadán login.',
															'Empty login.'),
	'empty_password'				=>			array('Nezadáno heslo.',
															'Empty password.'),
	'no_enter'						=>			array('Pøístup  odepøen.',
															'No enter'),
	'no_enter1'						=>			array('Zadal jste ¹patné heslo nebo pøihla¹ovací jméno',
															'Bad login or name'),
	// add_user.php
	'send_buttom'					=>			array('Odeslat',
															'Send'),
	'no_name'						=>			array('Zadejte jméno.',
															'Enter name.'),
	'no_name1'						=>			array('Jméno nesmí obsahovat bílé znaky.',
															'Name must not include white signs.'),
	'no_name2'						=>			array('Délka jména musí být v intervalu 2-45 znakù.',
															'Length of name must be in interval 2-45 symbols.'),
	'no_name3'						=>			array('Pøihla¹ovací jméno je ji¾ v databázi, pou¾ijte jiné.',
															'Entry name is in database now, use different.'),
	'no_surname'					=>			array('Zadejte pøíjmení.',
															'Enter name.'),
	'no_surname1'					=>			array('Pøíjmení nesmí obsahovat bílé znaky.',
															'Surname must not include white signs.'),
	'no_surname2'					=>			array('Délka pøíjmení musí být v intervalu 2-45 znakù.',
															'Length of surname must be in interval 2-45 symbols.'),
	'no_surname3'					=>			array('Pøíjmení je ji¾ v databázi, pou¾ijte jiné.',
															'Surname is in database now, use different.'),
	'no_login'						=>			array('Zadejte pøihla¹ovací jméno.',
															'Enter the entry name.'),
	'no_login1'						=>			array('Pøihla¹ovací jméno nesmí obsahovat bílé znaky.',
															'Entry name must not include white signs.'),
	'no_login2'						=>			array('Délka pøihla¹ovacího jména musí být v intervalu 2-20 znakù.',
															'Lenght entry name must be in interval 2-20 symbols.'),
	'no_login3'						=>			array('Pøihla¹ovací jméno nesmí obsahovat èeské znaky.',
															'Entry name must not include czech symbols.'),
	'no_login4'						=>			array('Pøihla¹ovací jméno je ji¾ v databázi, pou¾ijte jiné.',
															'Entry name is in database now, use different.'),
	'no_pass'						=>			array('Zadejte pøihla¹ovací heslo.',
															'Enter password.'),
	'no_pass1'						=>			array('Pøihla¹ovací heslo nesmí obsahovat bílé znaky.',
															'Entry password must not include white signs. '),
	'no_pass2'						=>			array('Délka pøihla¹ovacího hesla musí být v intervalu 4-20 znakù.',
															'Lenght entry password must be in interval 4-20 symbols.'),
	'no_pass3'						=>			array('Pøihla¹ovací heslo nesmí obsahovat èeské znaky.',
															'Entry password must not include czech signs.'),
	'no_email'						=>			array('E-mail nesmí být prázdný.',
															'E-mail must not be empty.'),
	'no_email1'						=>			array('E-mail je ve tvaru xx@xx.xx.',
															'E-mail must be xx@xx.xx.'),
	'no_email2'						=>			array('Délka e-mailu nesmí být del¹í ne¾ 100 znakù.',
															'Lenght of e-mail must not be longer than 100 symbols.'),
	'no_email3'						=>			array('E-mail nesmí obsahovat èeské znaky.',
															'E-mail must not include czech signs. '),
	'f_name'							=>			array('Jméno:',
															'Name:'),
	'f_surname'						=>			array('Pøíjmení:',
															'Surname:'),
	'f_login'						=>			array('Pøihla¹ovací jméno:',
															'Login:'),
	'f_pass'							=>			array('Heslo:',
															'Password:'),
	'f_old'							=>			array('Vìk:',
															'Age:'),
	'f_email'						=>			array('E-mail:',
															'E-mail:'),
// add_player.php
	'add_player'					=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání Hráèe: <font color=red>Èervená pole</font> jsou povinná.',
															'Please, fill data for addition player:'),
	'f_player_pozicion'			=>			array('Hrací pozice:',
															'Player pozition:'),
	'f_date'							=>			array('Datum narození (rrrr-mm-dd):',
															'Date birthday (rrrr-mm-dd):'),
	'f_home_club'					=>			array('Domácí klub:',
															'Home club:'),
	'f_hometown'					=>			array('Rodi¹tì:',
															'Hometown:'),
	'f_last_club'					=>			array('Minulý klub:',
															'Last club:'),
	'f_street'						=>			array('Ulice:',
															'Street:'),
	'f_city'							=>			array('Mìsto:',
															'City:'),
	'f_zip'							=>			array('PSÈ:',
															'Zip:'),
	'f_state'						=>			array('Stát:',
															'State:'),
	'f_family'						=>			array('Rodinný stav:',
															'Marital status:'),
	'f_team'							=>			array('Tým:',
															'Team:'),
				//dropdown
	'f_goalkeeper'					=>			array('brankáø',
															'goalkeeper'),
	'f_defenders'					=>			array('obránce',
															'defenders'),
	'f_midfielders'				=>			array('zálo¾ník',
															'midfielders'),
	'f_forward'						=>			array('útoèník',
															'forward'),
	'no_pozicion'					=>			array('Vyberte pozici hráèe:',
															'Choose player position:'),
	'no_family'						=>			array('Vyberte rodinný stav:',
															'Choose marital status:'),
	'no_date'						=>			array('Polo¾ka datum nesmí být prázdná.',
															'Date must not be empty.'),
	'no_date1'						=>			array('Zadali jste ¹patný formát data, musí být rok-mìsíc-den.',
															'Wrong format of date, must be year-month-day.'),
	'no_date2'						=>			array('Zadali jste ¹patný formát data, musí být (1900-2000)-(1-12)-(1-31).',
															'Wrong format of date, must be (1900-2000)-(1-12)-(1-31).'),
	'no_home_club'					=>			array('Název domácího klubu musí být krat¹í jak 40 znakù.',
															'Name of home club must be shorter than 40 symbols.'),
	'no_hometown'					=>			array('Rodi¹tì nesmí být prázdné.',
															'Hometown must not be empty.'),
	'no_hometown1'					=>			array('Rodi¹tì musí být krat¹í jak 25 znakù.',
															'Hometown must be shorter than 25 symbols.'),
	'no_last_club'					=>			array('Název bývalého klub musí být krat¹í jak 25 znakù.',
															'Name of last club must be shorter than 25 symbols.'),
	'no_street'						=>			array('Ulice musí být krat¹í jak 20 znakù.',
															'Street must be shorter than 20 symbols.'),
	'no_city'						=>			array('Mìsto musí být krat¹í jak 15 znakù.',
															'City must be shorter than 15 symbols.'),
	'no_zip'							=>			array('PSÈ musí být 4-5 znakù dlouhé a to jen èíslice.',
															'Zip must be longer 4-5 symbols and only numbers.'),
	'no_state'						=>			array('Zkratka státu musí mít délku 2-3 znaky.',
															'Short cut of state must be longer 2-3 symbols.'),
					//dropdown
	'f_unmarried'					=>			array('svobodný',
															'unmarried'),
	'f_married'						=>			array('¾enatý',
															'married'),
	'f_divorced'					=>			array('rozvedený',
															'divorced'),
	'f_widower'						=>			array('vdovec',
															'widower'),
	'no_team'						=>			array('Tým nesmí být prázdný.',
															'Team must not be empty.'),
	'no_team3'						=>			array('Domácí a hosté nemí být stejní.',
															'HOST x HOME.'),
	'no_team1'						=>			array('Zkratka týmu musí být v rozmezí 2-3 znaky.',
															'Short cut of team must be longer 2-3 symbols.'),
	'no_team2'						=>			array('Zkratka týmu nesmí obsahovat èeské znaky.',
															'Short of team must not include czech signs.'),
	'no_user'						=>			array('Hráè je ji¾ v databázi, zadejte jiné jméno a pøíjmení.',
															'Player is in database now, enter different name and surname.'),
// add_referee.php
	'add_referee'					=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání rozhodèího. <font color=red>Èervená pole</font> jsou povinná.',
															'Referee position:'),
	'no_referee'					=>			array('Rozhodèí je ji¾ v databázi, zadejte jiné jméno a pøíjmení.',
															'No czech char.'),
// add_team.php
	'add_team'						=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání týmu. <font color=red>Èervená pole</font> jsou povinná.',
															'Please, fill data for addition team:'),
	'no_team_add'					=>			array('Tým je ji¾ v databázi, zadejte jinou zkratku týmu a pøípadnì i název.',
															'No czech char.'),
	'no_team_add1'					=>			array(' Vybraná tabulka pro tým je ji¾ plná, pou¾ijte jinou tabulku.',
															'No czech char.'),
	'no_code'						=>			array('Zkratka týmu nemí být prázdná.',
															'No empty'),
	'no_code1'						=>			array('Délka zkratky týmu musí být v intervalu 2-3.',
															'2-3.'),
	'no_code2'						=>			array('Zkratka týmu nesmí obsahovat èeské znaky ani èíslice.',
															'No czech char.'),
	'no_state1'						=>			array('Název týmu nesmí být prázdný.',
															'25.'),
	'no_state2'						=>			array('Délka týmu musí být krat¹í jak 25.',
															'No czech char.'),
	'no_slogan'						=>			array('Délka sloganu musí být krat¹í jak 150.',
															'< 150.'),
	'no_group'						=>			array('Vyberte skupinu.',
															'Choose group.'),
	't_code'							=>			array('Zkratka státu:',
															'Code state:'),
	't_state'						=>			array('Název státu:',
															'State name:'),
	't_slogan'						=>			array('Slogan:',
															'Slogan:'),
	't_group'						=>			array('Skupina:',
															'Group:'),

	// add_match.php
	'match'							=>			array('Zápas je ji¾ v databázi.',
															'Match is in database now.'),
	'add_match'						=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání zápasu. <font color=red>Èervená pole</font> jsou povinná.',
															'Please, fill data for addition match.'),
	't_state'						=>			array('Název státu:',
															'State name:'),
	't_slogan'						=>			array('Slogan:',
															'Slogan:'),
	't_date'							=>			array('Datum zápasu (rrrr-mm-dd xx:xx):',
															'Date of match (yyyy-mm-dd xx:xx):'),
	't_type'							=>			array('Typ zápasu:',
															'Type of match:'),
	't_place'						=>			array('Místo zápasu:',
															'Place of match:'),
	't_score'						=>			array('Skóre:',
															'Score:'),
	'f_referee'						=>			array('Pomocný rozhodèí:',
															'Help referee:'),
	'f_referee2'					=>			array('Hlavní rozhodèí:',
															'Main referee:'),
	'f_referee3'					=>			array('1.Pomezní rozhodèí:',
															'Referee 1:'),
	'f_referee4'					=>			array('2.Pomezní rozhodèí:',
															'Referee 2:'),
	't_list'							=>			array('Soupiska domácích:',
															'Home\'s list:'),
	't_list2'						=>			array('Soupiska hostù:',
															'Guest\'s list:'),
	'no_referee'					=>			array('Vyberte rozhodèího:',
															'Choose referee:'),
	't_over_time'					=>			array('Nastavení:',
															'Over time:'),
	't_people'						=>			array('Poèet diváku:',
															'Number of watchers:'),
	'no_over_time'					=>			array('Nastavený èas musí obsahovat jen èísla a nesmí zaèínat 0.',
															'Over time must include only number and must not start by 0.'),
	'no_over_time1'				=>			array('Nastavený èas musí být men¹í ne¾ 20.',
															'Over time must be shorter than 20.'),
	'no_people'						=>			array('Poèet diváku obsahuje jen znaky 0-9.',
															'Only 0-9 char.'),
	'no_people1'					=>			array('Poèet diváku nesmí být vìt¹í jak 200 000,',
															'Number of watchers must not be bigger than 200 000.'),
	'no_type'						=>			array('Vyberte typ zápasu:',
															'Choose type of match:'),
	'no_score'						=>			array('Výsledek zápasu musí být ve tvaru xx:xx :',
															'Result of match must be xx:xx :'),
	'no_score1'						=>			array('Výsledek zápasu musí být ve tvaru xx:xx :',
															'Result of match must be xx:xx :'),
	'no_place'						=>			array('Místo konání zápasu nesmí být prázdné :',
															'Place of match must not be empty:'),
	'no_place1'						=>			array('Místo zápasu nesmí být del¹í jak 25 znakù.',
															'Place of match must not be longer than 25 symbols.'),
	'no_list'						=>			array('Soupisky mu¾stev nesmí být stejné.',
															'List must be diffrent.'),
	// add_action.php
	'no_minute'						=>			array('Minuta nesmí být prazdná.',
															'Minute must not be empty.'),
	'no_minute2'					=>			array('Jen èísla.',
															'Only number.'),
	'no_minute3'					=>			array('Minuta maximalne 120.',
															'Max 120.'),
	'no_player'						=>			array('Vyberte hráèe.',
															'Choose player.'),
	'no_action'						=>			array('Vyberte akci.',
															'Choose action.'),
	'no_team5'						=>			array('Vyberte tým.',
															'Choose team.'),
	'add_action'						=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání Akce: <font color=red>Èervená pole</font> jsou povinná.',
															'Please, fill data for addition action:'),
	'f_y_card'						=>			array('¾lutá karta',
															'yellow card'),
	'f_r_card'						=>			array('èervená karta',
															'red card'),
	'f_foul'							=>			array('faul',
															'foul'),
	'f_own_goal'					=>			array('vlastní gól',
															'own goal'),
	'f_goal'							=>			array('gól',
															'goal'),
	'f_corner'						=>			array('rohový kop',
															'corner kick'),
	'f_out'							=>			array('autové vhazování',
															'out'),
	'f_penalty'						=>			array('penalta',
															'penalty'),
	'f_offside'						=>			array('ofsajd',
															'offside'),
	'f_player'						=>			array('Hráè:',
															'Player:'),
	'f_match_type'					=>			array('Akce:',
															'Action:'),
	'f_minute'						=>			array('Minuta:',
															'Minute:'),
	'f_match'						=>			array('Zápas:',
															'Match:'),
	// default.php
	'no_escort'						=>			array('Èlen doprovodného týmu je ji¾ v databázi.',
															'Member of escort team is in database now.'),
	'add_escort'					=>			array('Prosím, vyplòte ní¾e uvedené údaje pro pøidání èlena do doprovodného týmu. <font color=red>Èervená pole</font> jsou povinná.',
															'Please, fill data for addition member for escort team:'),
	'f_escort_pozicion'			=>			array('Pozice v týmu:',
															'Team position:'),
						//dropdown
	'f_coach'						=>			array('trenér',
															'coach'),
	'f_assistant'					=>			array('asistent',
															'assistant'),
	'f_doctor'						=>			array('doktor',
															'doctor'),
	'f_maser'						=>			array('masér',
															'massager'),
	'f_group'						=>			array('skupina',
															'group'),
	'f_quarterfinal'				=>			array('ètvrtfinále',
															'quarterfinal'),
	'f_eightfinal'					=>			array('osmi finále',
															'eightfinal'),
   'f_semifinal'					=>			array('semifinále',
															'semifinal'),
	'f_final'						=>			array('finále',
															'final'),
   'f_guest_club' => array('Hosté:',
                               'Guest:'),
                                  // show_teams_new.php
   's_teams'      				 =>         array('Seznam týmù',
																'Teams'),
   's_code'      					 =>         array('Kod zìme',
																'Code of country'),
   's_stat'       				=>          array('Stát',
																'Country'),
   's_skupina'      				 =>         array('Skupina',
																'Group'),
    // show_actions_new.php
   's_actions'   					 =>     		 array('Seznam akcí',
																'Actions'),
   's_zapas' 						=>           array('Zápas',
																'Match'),
   's_typ' 							=>           array('Typ akce',
																'Type of action'),
   's_minuta' 						=>           array('Minuta',
																'Minute'),
   's_hrac'							=>           array('Hráè',
																'Player'),
   's_id'							=>           array('Id',
																'Id'),
    //show groups
   's_skA'							=>   			array('Skupina A','Group A'),
    's_skB'							=>   			array('Skupina B','Group B'),
    's_skC'							=> 		  	array('Skupina C','Group C'),
    's_skD'							=>   			array('Skupina D','Group D'),
    's_skE'							=>   			array('Skupina E','Group E'),
    's_skF'							=>   			array('Skupina F','Group F'),
    's_skG'							=>   			array('Skupina G','Group G'),
    's_skH'							=>   			array('Skupina H','Group H'),
    's_mesto'						=> 			array('Mesto: ','City: '),
    's_tym1'						=> 			array('Tým 1: ','Team 1: '),
    's_tym2'						=> 			array('Tým 2: ','Team 2: '),
    's_tym3'						=> 			array('Tým 3: ','Team 3: '),
    's_tym4'						=> 			array('Tým 4: ','Team 4: '),
	// players
	 's_meno'						=> 			array('Jméno','Name'),
	 's_priezv'    				=> 			array('Pøijmení','Surename'),
	 's_pozicia'					=> 			array('Pozice','Position'),
	 's_domklub'					=> 			array('Domácí klub','Home club'),
    's_team'						=> 			array('Tým','Team'),
    's_hraci'						=> 			array('Seznam hráèù','List of players'),
    's_edit'						=> 			array('Edituj','Edit'),
    's_editplayer'				=>          array('Edituj hráèe','Edit players'),
    's_ref'                   =>          array('Edituj rozhodèí','Edit referees'),
    's_editteams'             =>          array('Edituj týmy','Edit teams'),
    's_refshow'               =>          array('Seznam rozhodèí','List of referees'),
    //match
    's_date'                  =>          array('Datum','Date'),
    's_home'                  =>          array('Domáci','Home'),
    's_guest'                 =>          array('Hosté','Guest'),
    's_score'                 =>          array('Skóre','Score'),
    's_type'                  =>          array('Typ zápasu','Type of match'),
    's_time'                  =>          array('Èas','Time'),
    's_people'                =>          array('Lidé','People'),
    's_ref1'                  =>          array('Hlavní rozhodèí','Referee 1'),
    's_ref2'                  =>          array('Pomezní rozhodèí','Referee 2'),
    's_ref3'                  =>          array('Pomezní rozhodèí','Referee 3'),
    's_ref4'                  =>          array('Pomocný rozhodèí','Referee 4'),
    's_zapshow'               =>          array('Seznam zápasù','List of matches'),
	 's_zapedit'               =>          array('Edituj zápasy','Edit matches'),
	 's_akcedit'               =>          array('Edituj akce','Edit actions'),
    's_dopredit'              =>          array('Edituj doprovodní tým','Edit escort team'),
    's_dopshow'               =>          array('Doprovodní týmy','Escort teams'),
	// tabulka


	// tymy

	// HTML
   'html_name'                =>          array('Informacni system - Mistrostvi svet ave fotbalu','IIS - Champions League'),


'sentinel'           			 =>      	array('',''));
?>